---
#
# Ansible managed
#
repository:
  description: Change package manager configuration to install docs and manpages.
  homepage: https://robertdebock.nl/
  topics: containerdocs, ansible, molecule, tox, playbook, hacktoberfest
