---
#
# Ansible managed
#
language: python

os: linux
dist: xenial

python:
  - "3.9"

services:
  - docker

env:
  global:
    namespace="robertdebock"
  jobs:
    - image="alpine" tag="latest"
    - image="amazonlinux" tag="1"
    - image="amazonlinux" tag="latest"
    - image="centos" tag="7"
    - image="centos" tag="latest"
    - image="debian" tag="latest"
    - image="debian" tag="bullseye"
    - image="fedora" tag="32"
    - image="fedora" tag="latest"
    - image="fedora" tag="rawhide"
    - image="opensuse" tag="latest"
    - image="ubuntu" tag="latest"
    - image="ubuntu" tag="bionic"
    - image="ubuntu" tag="xenial"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - function retry { counter=0 ; until "$@" ; do exit=$? ; counter=$(($counter + 1)) ; if [ $counter -ge 3 ] ; then return $exit ; fi ; done ; return 0; } ; retry tox

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: "hFRLjSbR4m7SKxygsR9Wf9Bw8VmiNv1GCqRjppOA/YjZxF3soFR+kQXVXkKP2WSZ9SEltjx8FY/lDk2AW+anXJrvVtqZCxWrQ/3B+XV0EhjHnHIRZFz+sJ0j3AVdLFOet8GSOqzV2lhHMwgYSqcjIeTlgzMiGuznPv7g0dV9YvqAh4x+islXt7QWvOvx9M5W0lCvy05br/NrurhozwzqC/tz5jR1oi/zczGsg5M7hfoPvRiefeTFCfQzrIyMvdKX0yfPHeg+C36Cew+wkxAaLsu2WdcJtP/+sHCzxWmnRf6xFEEi98GsPB6T/R/mD3A8sgBnsHdXSPLP1ti1ETbU7ZSc1Xm7fLPiEQsjWsQSA0KEqXFcypdDuq3zRKMP+mqPjl1QKArWZEgDEvp8Iu8VgeYhTGZOHh/9QvY1GkLkp7oWkRAN7c8GLLnNuc0w/ZFPuL+xNrtblxQT200hd/vzG5PxvYsI2kvIl4awZma+RHhcbpLnS/nZANVY+gO1I49G1WXcNgGFD3EWt+xcWNv7N69HM7EtHirgTXZN5n7xgbf6VX9yzv/XGuIq5HM4D+QhHObUurEi5fV5ycSdtxVCzVseJ00sn4H74yLdEgWQEQpTyLUvVlX6yhnnF81tc3NZk9+V0gwDdBMs5tA1aPj9oEInnndHX3vz60YVd5sdrBw="
    on_success: change
    template: "%{result}: %{repository_slug}@%{branch}, build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>)"
  email: false
