---
# tasks file for container_docs
- name: unset nodocs flag in yum.conf
  replace:
    path: /etc/yum.conf
    regexp: nodocs
  when:
    - ansible_pkg_mgr == "yum"

- name: unset nodocs flag in dnf.conf
  replace:
    path: /etc/dnf/dnf.conf
    regexp: nodocs
  when:
    - ansible_pkg_mgr == "dnf"

- name: status of /etc/dpkg/dpkg.cfg.d/excludes
  stat:
    path: /etc/dpkg/dpkg.cfg.d/excludes
  register: status_of_etc_dpkg_dpkg_cfg_d_excludes

- name: unset excludes /usr/share/doc in dpkg.cfg.d/excludes
  replace:
    path: /etc/dpkg/dpkg.cfg.d/excludes
    regexp: '^(path-exclude=.*)'
    replace: '#\1'
  when:
    - ansible_pkg_mgr == "apt"
    - status_of_etc_dpkg_dpkg_cfg_d_excludes.stat.exists
